config/routes.rb
Rails.application.routes.draw do
  post 'reservations', to: 'reservations#create'
  post 'reservations/:id/cancel', to: 'reservations#cancel', as: 'cancel_reservation'

  post 'become_host', to: 'hosts#become_host', as: 'become_host'
  get 'connected', to: 'hosts#connected', as: 'connected'

  post 'reviews', to: 'reviews#create'

  resources :places, only: [:show, :create]
  resources :favorites, only: [:create, :destroy]

  scope '/profile' do
    get 'places', to: 'profile#places', as: 'my_places'
    get 'places/new', to: 'places#new', as: 'new_place'
    get 'favorites', to: 'profile#favorites', as: 'my_favorites'
    get 'reservations', to: 'profile#reservations', as: 'my_reservations'
    get 'reservations/:id', to: 'profile#reservation', as: 'reservation'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register',
    edit: 'profile'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'webhooks', to: 'webhooks#create'
  post 'webhooks/connect', to: 'webhooks#connect'

  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_favorite_button.html.erb
<% if signed_in? %>
  <%= turbo_frame_tag "#{dom_id(place)}_favorite" do %>
    <% if favorite.nil? %>
      <%= button_to favorites_path, params: { favorite: { place_id: place.id } }, method: :post do %>
        <svg class="w-8 h-8 text-black fill-current stroke-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
        </svg>
      <% end %>
    <% else %>
      <%= button_to favorite_path(favorite), method: :delete do %>
        <svg class="w-8 h-8 text-red-500 fill-current stroke-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
        </svg>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_profile_nav.html.erb
  <nav class="border-b border-gray-700 mb-6 cols-span-1">
  <ul class="flex">
    <li>
      <%= link_to edit_user_registration_path, class: "px-4 py-2 font-semibold flex gap-2 #{current_page?(edit_user_registration_path) ? 'border-b-2 border-blue-500 text-blue-500' : 'text-gray-500 hover:text-gray-600'}" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0012 15.75a7.488 7.488 0 00-5.982 2.975m11.963 0a9 9 0 10-11.963 0m11.963 0A8.966 8.966 0 0112 21a8.966 8.966 0 01-5.982-2.275M15 9.75a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
        <span>Account</span>
      <% end %>
    </li>
    <li>
      <%= link_to my_places_path, class: "px-4 py-2 font-semibold flex gap-2 #{current_page?(my_places_path) ? 'border-b-2 border-blue-500 text-blue-500' : 'text-gray-500 hover:text-gray-600'}" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 21v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21m0 0h4.5V3.545M12.75 21h7.5V10.75M2.25 21h1.5m18 0h-18M2.25 9l4.5-1.636M18.75 3l-1.5.545m0 6.205l3 1m1.5.5l-1.5-.5M6.75 7.364V3h-3v18m3-13.636l10.5-3.819" />
        </svg>
        <span>Places</span>
      <% end %>
    </li>
    <li>
      <%= link_to my_favorites_path, class: "px-4 py-2 font-semibold flex gap-2 #{current_page?(my_favorites_path) ? 'border-b-2 border-blue-500 text-blue-500' : 'text-gray-500 hover:text-gray-600'}" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
        </svg>
        <span>Favorites</span>
      <% end %>
    </li>
  </ul>
</nav>