config/routes.rb
Rails.application.routes.draw do
  post 'reservations', to: 'reservations#create'
  post 'reservations/:id/cancel', to: 'reservations#cancel', as: 'cancel_reservation'

  post 'become_host', to: 'hosts#become_host', as: 'become_host'
  get 'connected', to: 'hosts#connected', as: 'connected'

  post 'reviews', to: 'reviews#create'

  resources :places, only: [:show, :create]
  resources :favorites, only: [:create, :destroy]

  scope '/profile' do
    get 'places', to: 'profile#places', as: 'my_places'
    get 'places/new', to: 'places#new', as: 'new_place'
    get 'favorites', to: 'profile#favorites', as: 'my_favorites'
    get 'reservations', to: 'profile#reservations', as: 'my_reservations'
    get 'reservations/:id', to: 'profile#reservation', as: 'reservation'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register',
    edit: 'profile'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'webhooks', to: 'webhooks#create'
  post 'webhooks/connect', to: 'webhooks#connect'

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @places = Place.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6"
>
  <% @places.each do |place| %>
    <article
        data-controller="place"
        data-place-latitude-value="<%= place.latitude %>"
        data-place-longitude-value="<%= place.longitude %>"
        class="relative"
      >
      <div class="absolute top-2 right-2 z-30">
        <% favorite = current_user.favorites.find_by(place: place) if signed_in? %>
        <%= render 'shared/favorite_button', favorite: favorite, place: place, render_text: false %>
      </div>
      <%= link_to place_path(place), class: 'relative' do %>
        <div>
          <% if place.images.attached? %>
            <%= image_tag place.default_image, class: "rounded-md h-56 w-full object-cover" %>
          <% end %>
        </div>
        <div class="flex justify-between mt-2">
          <h1 class="font-semibold">
            <%= place.city %>, <%= place.country %>
          </h1>
          <p class="text-gray-700 flex gap-1 items-center">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-4 h-4">
              <path fill-rule="evenodd" d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z" clip-rule="evenodd" />
            </svg>
            <%= place.average_vote %>
          </p>
        </div>
        <p data-place-target="distance" class="text-gray-700">
          Calculating distance...
        </p>
        <p>
          <span class="font-semibold">
            $<%= place.price %>
          </span>
          night
        </p>
      <% end %>
    </article>
  <% end %>
</div>