config/routes.rb
Rails.application.routes.draw do
  post 'reservations', to: 'reservations#create'
  post 'reservations/:id/cancel', to: 'reservations#cancel', as: 'cancel_reservation'

  post 'become_host', to: 'hosts#become_host', as: 'become_host'
  get 'connected', to: 'hosts#connected', as: 'connected'

  post 'reviews', to: 'reviews#create'

  resources :places, only: [:show, :create]
  resources :favorites, only: [:create, :destroy]

  scope '/profile' do
    get 'places', to: 'profile#places', as: 'my_places'
    get 'places/new', to: 'places#new', as: 'new_place'
    get 'favorites', to: 'profile#favorites', as: 'my_favorites'
    get 'reservations', to: 'profile#reservations', as: 'my_reservations'
    get 'reservations/:id', to: 'profile#reservation', as: 'reservation'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register',
    edit: 'profile'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'webhooks', to: 'webhooks#create'
  post 'webhooks/connect', to: 'webhooks#connect'

  # Defines the root path route ("/")
  root "home#index"
end

app/models/place.rb
class Place < ApplicationRecord
  validates :name, 
    :headline,
    :description,
    :price,
    :cleaning_fee,
    :max_guests,
    :rooms,
    :beds,
    :baths,
    :min_reservation_days,
    :address_1,
    presence: true
  validates :price,
    :max_guests,
    :rooms,
    :beds,
    :baths,
    :min_reservation_days,
    numericality: { greater_than: 0 }

  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :host, class_name: 'User'
  has_many_attached :images, dependent: :destroy

  geocoded_by :address

  after_validation :geocode

  def address
    [address_1, address_2, city, state, postal_code, country].compact.join(', ')
  end

  def default_image
    images.first
  end

  def user_is_guest?(user)
    reservations.where(user: user).any?
  end
  
  def user_already_reviewed?(user)
    reviews.where(user: user).any?
  end

  def reviewable_by?(user)
    user_is_guest?(user) && !user_already_reviewed?(user) && reservations.where(user: user).last.checkout < Date.today
  end


  def average_vote
    reviews.average(:vote).to_i
  end

  def first_available_date
    # if there are no reservations, return today
    paid_reservations = reservations.where(status: :paid)

    return Date.today if paid_reservations.empty?

    # if there are reservations, return the first available date
    paid_reservations.order(:checkout).last.checkout + 1
  end

  def unavaible_dates
    reservations.where(status: :paid).order(:checkin).map do |reservation|
      if reservation.checkin >= Date.today
        { from: reservation.checkin, to: reservation.checkout }
      end
    end
  end
end

app/controllers/place_controller.rb
class PlaceController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def show
    @place = Place.find(params[:id])
    @favorite = current_user.favorites.find_by(place_id: @place.id) if current_user
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    @place.host = current_user

    if @place.save
      redirect_to show_place_path(@place)
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(
      :name, 
      :headline, 
      :description, 
      :price,
      :cleaning_fee,
      :max_guests,
      :rooms,
      :beds,
      :baths,
      :min_reservation_days, 
      :address_1, 
      :address_2, 
      :postal_code, 
      :city, 
      :country, 
      :state, 
      :latitude, 
      :longitude, 
      images: [])
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create]

  def index
    @places = Place.where(host: current_user)
  end

  def show
    @place = Place.find(params[:id])
    @favorite = current_user.favorites.find_by(place_id: @place.id) if current_user
    @reservation = Reservation.new
  end

  def new
    @place = Place.new
    authorize @place
  end

  def create
    @place = Place.new(place_params)
    @place.host = current_user

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def place_params
    params.require(:place).permit(
      :name, 
      :headline, 
      :description, 
      :price,
      :cleaning_fee,
      :max_guests,
      :rooms,
      :beds,
      :baths,
      :min_reservation_days, 
      :address_1, 
      :address_2, 
      :postal_code, 
      :city, 
      :country, 
      :state, 
      :latitude, 
      :longitude, 
      images: [])
  end
end

app/helpers/place_helper.rb
module PlaceHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place) do |form| %>
  <div class="flex flex-col gap-4">
    <div class="grid grid-cols-2 gap-4">
      <div class="flex flex-col">
        <%= form.label :name, class: 'font-medium mb-1' %>
        <%= form.text_field :name, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full' %>
        <p class="text-xs text-red-500 italic">
          <%= place.errors.full_messages_for(:name).first %>
        </p>
      </div>
      <div class="flex flex-col">
        <%= form.label :headline, class: 'font-medium mb-1' %>
        <%= form.text_field :headline, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full' %>
        <p class="text-xs text-red-500 italic">
          <%= place.errors.full_messages_for(:headline).first %>
        </p>
      </div>
    </div>
    <div class="flex flex-col">
      <%= form.label :description, class: 'font-medium mb-1' %>
      <%= form.text_area :description, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full' %>
      <p class="text-xs text-red-500 italic">
        <%= place.errors.full_messages_for(:description).first %>
      </p>
    </div>
    <div class="flex flex-col"  
      data-controller="places"
      data-action="map-loaded@window->places#initMap"
      >
      <%= form.label :address, class: 'font-medium mb-1' %>
      <input autocomplete="false", data-places-target="input" data-action="keydown->places#keydown" class='p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full' />
      <p class="text-xs text-red-500 italic">
        <%= place.errors.full_messages_for(:address_1).first %>
      </p>
      <input type="hidden" name="place[address_1]" data-places-target="line1">
      <input type="hidden" name="place[address_2]" data-places-target="line2">
      <input type="hidden" name="place[postal_code]" data-places-target="postal_code">
      <input type="hidden" name="place[city]" data-places-target="city">
      <input type="hidden" name="place[state]" data-places-target="state">
      <input type="hidden" name="place[country]" data-places-target="country">
      <input type="hidden" name="place[latitude]" data-places-target="lat">
      <input type="hidden" name="place[longitude]" data-places-target="lng">
    </div>
    <div class="grid grid-cols-2 gap-4">
      <div class="flex flex-col">
        <%= form.label :price, class: 'font-medium mb-1' %>
        <%= form.number_field :price, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full' %>
        <p class="text-xs text-red-500 italic">
          <%= place.errors.full_messages_for(:price).first %>
        </p>
      </div>
      <div class="flex flex-col">
        <%= form.label :cleaning_fee, class: 'font-medium mb-1' %>
        <%= form.number_field :cleaning_fee, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full' %>
        <p class="text-xs text-red-500 italic">
          <%= place.errors.full_messages_for(:cleaning_fee).first %>
        </p>
      </div>
    </div>
    <div class="grid grid-cols-2 lg:grid-cols-5 gap-4">
      <div class="flex flex-col">
        <%= form.label :max_guests, class: 'font-medium mb-1' %>
        <%= form.number_field :max_guests, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full', value: "1"%>
        <p class="text-xs text-red-500 italic">
          <%= place.errors.full_messages_for(:max_guests).first %>
        </p>
      </div>
      <div class="flex flex-col">
        <%= form.label :rooms, class: 'font-medium mb-1' %>
        <%= form.number_field :rooms, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full', value: "1"%>
        <p class="text-xs text-red-500 italic">
          <%= place.errors.full_messages_for(:rooms).first %>
        </p>
      </div>
      <div class="flex flex-col">
        <%= form.label :beds, class: 'font-medium mb-1' %>
        <%= form.number_field :beds, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full', value: "1"%>
        <p class="text-xs text-red-500 italic">
          <%= place.errors.full_messages_for(:beds).first %>
        </p>
      </div>
      <div class="flex flex-col">
        <%= form.label :baths, class: 'font-medium mb-1' %>
        <%= form.number_field :baths, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full', value: "1"%>
        <p class="text-xs text-red-500 italic">
          <%= place.errors.full_messages_for(:baths).first %>
        </p>
      </div>
      <div class="flex flex-col">
        <%= form.label :min_reservation_days, class: 'font-medium mb-1' %>
        <%= form.number_field :min_reservation_days, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full', value: "1"%>
        <p class="text-xs text-red-500 italic">
          <%= place.errors.full_messages_for(:min_reservation_days).first %>
        </p>
      </div>
    </div>
    <div class="flex flex-col" data-controller="image-upload">
      <%= form.label :images, class: 'font-medium' %>
      <div class="border rounded-md min-h-32 my-1 flex flex-wrap gap-2" data-image-upload-target="preview">
      </div>
      <%= form.file_field :images, multiple: true, class: 'p-2 rounded-md border border-gray-400 hover:border-gray-500 w-full', data: {
        "image-upload-target": "input",
        action: "change->image-upload#uploadMultiple"
      } %>
    </div>
    <%= form.submit 'Create', class: 'py-2 rounded-md bg-blue-500 hover:bg-blue-400 w-full text-white font-semibold cursor-pointer' %>
  </div>
<% end %>

app/views/places/_map.html.erb
<section 
  data-controller="map"
  data-action="map-loaded@window->map#initMap"
  data-map-latitude-value="<%= place.latitude %>" 
  data-map-longitude-value="<%= place.longitude %>"
  >
  <h1 class="font-semibold text-2xl">Where you'll be</h1>
  <div class="mt-4 w-full h-96" data-map-target="map"></div>
</section>

app/views/places/_reservation.html.erb
<div class="border border-gray-300 rounded-md shadow-lg p-6"
  data-controller="reservation"
  data-reservation-price-value="<%= @place.price %>"
  data-reservation-min-nights-value="<%= @place.min_reservation_days %>"
  data-reservation-cleaning-fee-value="<%= @place.cleaning_fee %>"
  data-reservation-first-date-available-value="<%= @place.first_available_date %>"
>
  <p class="text-xl">
    <span class="font-semibold"><%= number_to_currency(@place.price, precision: 0) %></span>
    <span class="text-gray-600">night</span>
  </p>
  <p class="text-sm text-gray-600 mb-6">(minimum of <%= @place.min_reservation_days %> nights)</p>
  <%= form_with(model: @reservation, data: { turbo: false }) do |form| %>
    <input type="hidden" name="reservation[place_id]" value="<%= @place.id %>"/>
    <div class="grid grid-cols-2">
      <%= form.date_field :checkin,
        class: "border border-gray-500 rounded-tl-md p-3",
        data: {
          "reservation-target": "checkin",
          action: "change->reservation#checkinChanged"
        } 
      %>
      <%= form.date_field :checkout,
        class: "border border-gray-500 rounded-tr-md p-3",
        data: {
          "reservation-target": "checkout",
          action: "change->reservation#checkoutChanged"
        } 
      %>
    </div>
    <%= form.number_field :guests, placeholder: "Number of guests", value: "#{@place.max_guests}", min: "1", max: "#{@place.max_guests}", class: "border border-gray-500 rounded-b-md w-full p-3" %>
    <% if signed_in? %>
      <%= form.submit 'Reserve', class: "mt-4 p-3 rounded-md bg-red-500 hover:bg-red-600 w-full text-white font-semibold cursor-pointer" %>
    <% else %>
      <%= link_to 'Sign in to reserve', new_user_session_path, class: "block text-center mt-4 p-3 rounded-md bg-red-500 hover:bg-red-600 w-full text-white font-semibold cursor-pointer" %>
    <% end %>
    <p class="mt-2 text-gray-500 text-center">You won't be charged</p>
  <% end %>
  <div class="flex flex-col space-y-2 text-lg text-gray-600 mt-6">
    <div class="flex justify-between">
      <p><%= number_to_currency(@place.price, precision: 0) %> x <span data-reservation-target="totalNights"></span> nights</p>
      <p data-reservation-target="totalPerNight"><%= number_to_currency(@place.price * 5, precision: 0) %></p>
    </div>
    <div class="flex justify-between">
      <p>Cleaning fee</p>
      <p><%= number_to_currency(@place.cleaning_fee, precision: 0) %></p>
    </div>
    <div class="h-[1px] bg-gray-500 my-6"></div>
    <div class="flex justify-between font-semibold">
      <p>Total</p>
      <p data-reservation-target="totalPrice"><%= number_to_currency(@place.price * 5 + @place.cleaning_fee, precision: 0) %></p>
    </div>
  </div>
</div>

app/views/places/create.html.erb
<h1>Place#create</h1>
<p>Find me in app/views/place/create.html.erb</p>

app/views/places/index.html.erb
<%= render "shared/profile_nav" %>
<header class="flex items-center justify-between">
  <h1 class="text-lg font-semibold">My Places</h1>
  <% if current_user.is_host? %>
    <%= link_to 'Host a Place', new_place_path, class: 'px-3 py-2 rounded-md bg-blue-400 hover:bg-blue-500 cursor-pointer text-white font-semibold' %>
  <% end %>
</header>
<% if current_user.is_host? and current_user.charges_enabled? %>
  <% if @places.empty? %>
    <p class="text-gray-600 mt-6">You haven't hosted any places yet.</p>
  <% else %>
    <div class="grid grid-cols-1 gap-6 mt-6">
      <% @places.each do |place| %>
        <%= render "place", place: place %>
      <% end %>
    </div>
  <% end %>
<% else %>
  <div class="flex flex-col items-center justify-center">
    <p class="text-gray-600 mt-6 text-center">You haven't become a host yet. Connect to your Stripe account.</p>
    <%= button_to 'Become a Host', become_host_path, data: { turbo: false }, class: 'p-3 rounded-md bg-blue-400 hover:bg-blue-500 active:bg-blue-600 text-white font-semibold mt-2' %>
  </div>
<% end %>

app/views/places/new.html.erb
<%= render "profile/nav" %>
<h1 class="text-lg font-semibold">New Place</h1>
<p class="text-gray-600 mb-6">Use this form to host a Place</p>
<%= render "form", place: @place %>

app/views/places/show.html.erb
<header class="mb-6 flex justify-between items-end">
  <div>
    <h1 class="text-xl md:text-3xl font-semibold">
      <%= @place.headline %>
    </h1>
    <p>
      <%= @place.city %>, <%= @place.state %>, <%= @place.country %>
    </p>
  </div>
  <div>
    <%= render 'shared/favorite_button', favorite: @favorite, place: @place, render_text: true %>
  </div>
</header>
<div>
  <% if @place.images.attached? %>
    <div class="grid grid-cols-2 gap-1 md:gap-2">
      <%= image_tag @place.default_image, class: 'w-full h-full object-cover rounded-md' %>
      <div class="grid grid-cols-2 gap-1 md:gap-2">
        <% @place.images.drop(1).first(4).each do |image| %>
          <%= image_tag image, class: 'w-full h-full object-cover rounded-md' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div class="grid grid-cols-1 lg:grid-cols-3 lg:gap-24 mt-6">
  <div class="col-span-2 mb-6 lg:mb-0">
    <header class="flex justify-between gap-4 mb-8">
      <div class="flex flex-col">
        <h2 class="text-xl font-medium">
          <%= @place.name %> (Hosted by <%= @place.host.name %>)
        </h2>
        <div class="flex text-center divide-x divide-gray-400 text-xs sm:text-base mt-2">
          <p class="px-2">
            <%= pluralize(@place.max_guests, 'guest') %>
          </p>
          <p class="px-2">
            <%= pluralize(@place.rooms, 'room') %>
          </p>
          <p class="px-2">
            <%= pluralize(@place.beds, 'bed') %>
          </p>
          <p class="px-2">
            <%= pluralize(@place.baths, 'bath') %>
          </p>
        </div>
      </div>
      <%= image_tag @place.host.user_avatar, class: 'w-16 h-16 rounded-full' %>
    </header>
    <p>
      <%= @place.description %>
    </p>
  </div>
  <div class="">
    <%= render "reservation" %>
  </div>
</div>
<div class="h-[1px] bg-gray-300 my-12 w-full"></div>
<%= render 'reviews/reviews', place: @place %>
<div class="h-[1px] bg-gray-300 my-12 w-full"></div>
<%= render 'map', place: @place %>