config/routes.rb
Rails.application.routes.draw do
  post 'reservations', to: 'reservations#create'
  post 'reservations/:id/cancel', to: 'reservations#cancel', as: 'cancel_reservation'

  post 'become_host', to: 'hosts#become_host', as: 'become_host'
  get 'connected', to: 'hosts#connected', as: 'connected'

  post 'reviews', to: 'reviews#create'

  resources :places, only: [:show, :create]
  resources :favorites, only: [:create, :destroy]

  scope '/profile' do
    get 'places', to: 'profile#places', as: 'my_places'
    get 'places/new', to: 'places#new', as: 'new_place'
    get 'favorites', to: 'profile#favorites', as: 'my_favorites'
    get 'reservations', to: 'profile#reservations', as: 'my_reservations'
    get 'reservations/:id', to: 'profile#reservation', as: 'reservation'
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register',
    edit: 'profile'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post 'webhooks', to: 'webhooks#create'
  post 'webhooks/connect', to: 'webhooks#connect'

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/_navbar.html.erb
<nav class="border-b border-gray-300 py-4 bg-white">
  <div class="max-w-7xl mx-auto flex items-center justify-between px-4">
    <%= link_to root_path do %>
      <%= image_tag "airbnb-full.svg", alt: 'Airbnb', class: 'w-24 hidden lg:block' %>
      <%= image_tag "airbnb-icon.svg", alt: 'Airbnb', class: 'w-10 block lg:hidden' %>
    <% end %>
    <div data-controller="menu" class="relative">
      <button data-menu-target="button" data-action="click->menu#toggle keydown.esc->menu#close click@window->menu#close" class="border border-gray-300 hover:shadow-lg transition-all rounded-full flex items-center gap-3 py-1 px-2">
        <svg class="w-7 h-7" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
        </svg>
        <%= image_tag current_user.user_avatar, class: 'w-9 rounded-full' %>
      </button>
      <ul
        data-menu-target="menu"
        class="hidden absolute z-50 ring-1 ring-gray-300 bg-white rounded-md shadow-lg mt-2 w-56 right-0 origin-top-right overflow-hidden" 
        role="menu"
        tabindex="-1"
      >
        <% if user_signed_in? %>
          <li>
            <%= link_to "Profile", edit_user_registration_path, class: 'text-gray-700 block px-4 py-3 text-sm hover:bg-gray-100' %>
          </li>
          <li>
            <%= link_to "Your reservations", my_reservations_path, class: 'text-gray-700 block px-4 py-3 text-sm hover:bg-gray-100' %>
          </li>
          <li>
            <%= link_to "#{current_user.is_host? ? 'Your places' :  'Become a host'}", my_places_path, class: 'text-gray-700 block px-4 py-3 text-sm hover:bg-gray-100' %>
          </li>
          <li>
            <%= link_to "Sign out", destroy_user_session_path, data: {'turbo-method': :delete}, class: 'border-t border-gray-300 text-red-400 block px-4 py-3 text-sm hover:bg-gray-100' %>
          </li>
        <% else %>
          <li>
            <%= link_to "Register", new_user_registration_path, class: 'text-gray-700 block px-4 py-3 text-sm hover:bg-gray-100' %>
          </li>
          <li>
            <%= link_to "Login", new_user_session_path, class: 'text-gray-700 block px-4 py-3 text-sm hover:bg-gray-100' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Rails.application.credentials[:google][:api_key]}&libraries=places&callback=initMap", defer: true %>
    <body>
      <%= render "layouts/navbar" %>
      <main class="max-w-7xl mx-auto px-4 py-8">
        <%= yield %>
      </main>
    </body>
  </html>